# Generated by Django 2.2.4 on 2019-08-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('S', 'Shirts'), ('Sk', 'Skirts'), ('A', 'Accessories'), ('P', 'Pants'), ('T', 'T-shirts')], max_length=2)),
                ('label', models.CharField(choices=[('M', 'Men'), ('L', 'Ladies'), ('K', 'Kids')], default='L', max_length=2)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
