# Generated by Django 2.2.4 on 2019-08-20 12:00

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(choices=[('A', 'Armani'), ('V', 'Versace'), ('J', 'Jack Honey'), ('C', 'Carlo Bruni')], default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('W', 'White'), ('B', 'Blue'), ('G', 'Green'), ('Y', 'Yellow'), ('R', 'Red')], default='W', max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newer', to='shop.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='older', to='shop.Item'),
        ),
    ]
